### ISSUE TITLE
Help Wanted Tag?

### ISSUE THREAD

**Issue by nickumia** [riiswa/colony-ant-simulator#10]
Hello Fellow Pythonite!

I found this repo through https://github.com/topics/help-wanted?l=python because it's tagged with `help wanted`.  Is there something that you needed help with?

I haven't run the program, but it does seem pretty cool.

![image](https://user-images.githubusercontent.com/10157100/194737150-901e484a-2940-4bd8-9e65-34107ec44b59.png)

**Comment by riiswa** [comment]
Haha it's a really old project, with very bad code in terms of performance, if you want, you can try to improve it :)

**Comment by nickumia** [comment]
Fair enough haha, I took a crack at it.  You're welcome to outright reject it or offer additional suggestions.  It was pretty fun learning the code and it was written well, so it wasn't too hard to figure it out.  Looking forward to your review 😅 
- https://github.com/riiswa/colony-ant-simulator/pull/11
