### ISSUE TITLE
New feature proposition: Simulation mode + Minor suggestions

### ISSUE THREAD

**Issue by em-oaken** [riiswa/colony-ant-simulator#13]
Hi there,

I was thinking to add the simulation mode as a new feature. With for now 2 options:
- The existing simulation mode
- Another simulation mode where:
  - ants' energy decreases if they get no food. They may die or restore their energy if they find the nest or food
  - Nest accumulates food. Food in the nest disappear (due to consumption, but also expires, etc...)
  - The nest produces new ants if food level is enough

Besides, what do you think about having >1 food on the board?

Last, do you mind if I reverse default colours to something brighter? Will be easier to spot the ants.

Have a good Friday!
Em

**Comment by riiswa** [comment]
Sorry for my late reply, but I really love your ideas! Tell me if you need help to implement it :)
